spring.application.name=ai-chatbot-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/aichatbot
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

app.cors.allowed-origins=http://localhost:5173

server.error.include-message=never

openai.api.key=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
openai.model=stepfun/step-3.5-flash:free